classdef marginEstimationTest < matlab.unittest.TestCase
    %MARGINESTIMATIONTEST Exercise supported parametric margin adapters.

    properties (TestParameter)
        margin = struct( ...
            "normal","norm", ...
            "exponential","exp", ...
            "beta","beta", ...
            "gamma","gamma", ...
            "lognormal","lnorm", ...
            "weibull","weibull", ...
            "student","t", ...
            "cauchy","cauchy", ...
            "chiSquared","chisq", ...
            "fDistribution","f");
    end

    methods (TestClassSetup)
        function addToolbox(testCase)
            root=fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(root,"src")));
            testCase.applyFixture(matlab.unittest.fixtures.SuppressedWarningsFixture( ...
                "stats:tlsfit:IterLimit"));
        end
    end

    methods (Test)
        function marginProducesFiniteStatistic(testCase,margin)
            first=linspace(0.1,0.9,24).';
            x=[first,0.15+0.7*first.^1.2];
            actual=gofcopula.gofCvM("normal",x,M=0,Param=0.2, ...
                ParamEst=false,DFEst=false,Margins=margin);
            testCase.verifyTrue(isfinite(actual.Tests.Statistic));
        end
    end
end
