classdef publicTestsSmokeTest < matlab.unittest.TestCase
    %PUBLICTESTSSMOKETEST Exercise every public statistical test entry point.

    properties (TestParameter)
        statisticCase = struct( ...
            "cvm",struct(Name="gofCvM"), ...
            "ks",struct(Name="gofKS"), ...
            "kendallCvm",struct(Name="gofKendallCvM"), ...
            "kendallKs",struct(Name="gofKendallKS"), ...
            "rosenblattSnB",struct(Name="gofRosenblattSnB"), ...
            "rosenblattSnC",struct(Name="gofRosenblattSnC"), ...
            "rosenblattGamma",struct(Name="gofRosenblattGamma"), ...
            "rosenblattChisq",struct(Name="gofRosenblattChisq"), ...
            "kernel",struct(Name="gofKernel"), ...
            "white",struct(Name="gofWhite"), ...
            "piosTn",struct(Name="gofPIOSTn"), ...
            "piosRn",struct(Name="gofPIOSRn"), ...
            "archmSnB",struct(Name="gofArchmSnB"), ...
            "archmSnC",struct(Name="gofArchmSnC"), ...
            "archmGamma",struct(Name="gofArchmGamma"), ...
            "archmChisq",struct(Name="gofArchmChisq"));
    end

    methods (TestClassSetup)
        function addToolbox(testCase)
            root=fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(root,"src")));
        end
    end

    methods (Test)
        function fixedClaytonTestReturnsFiniteStatistic(testCase,statisticCase)
            u=[.1 .2;.2 .4;.4 .3;.6 .8;.8 .7;.9 .95];
            functionHandle=str2func("gofcopula."+statisticCase.Name);
            actual=functionHandle("clayton",u,M=0,Param=1,ParamEst=false, ...
                DFEst=false,Margins="none",Seed=2,MJ=20,IntegrationNodes=6);
            testCase.verifyClass(actual,"gofcopula.GofResult");
            testCase.verifyTrue(isfinite(actual.Tests.Statistic));
        end

        function customTestReturnsFiniteStatistic(testCase)
            u=[.1 .2;.2 .4;.4 .3;.6 .8;.8 .7;.9 .95];
            actual=gofcopula.gofCustomTest("clayton",u,M=0,Param=1, ...
                ParamEst=false,DFEst=false,Margins="none",Seed=2, ...
                CustomTest=@(sample,model) sum(sample(:))+0*model.Theta);
            testCase.verifyTrue(isfinite(actual.Tests.Statistic));
        end

        function combinedAnalysisAddsHybridRow(testCase)
            u=[.1 .2;.2 .4;.4 .3;.6 .8;.8 .7;.9 .95];
            actual=gofcopula.gof(u,Copulas="clayton", ...
                Tests=["gofCvM","gofKS"],M=0,Param=1,ParamEst=false, ...
                DFEst=false,Margins="none",Seed=2);
            testCase.verifyTrue(any(startsWith(actual.Tests.Name,"hybrid")));
        end
    end
end
