classdef rOracleTest < matlab.unittest.TestCase
    %RORACLETEST Cross-language regression tests against gofCopula 0.4-3.

    properties (Access=private)
        Oracle
    end

    properties (TestParameter)
        familyCase = struct( ...
            "normal",struct(Name="normal"), ...
            "student",struct(Name="t"), ...
            "clayton",struct(Name="clayton"), ...
            "gumbel",struct(Name="gumbel"), ...
            "frank",struct(Name="frank"), ...
            "joe",struct(Name="joe"), ...
            "amh",struct(Name="amh"), ...
            "galambos",struct(Name="galambos"), ...
            "huslerReiss",struct(Name="huslerreiss"), ...
            "tawn",struct(Name="tawn"), ...
            "tev",struct(Name="tev"), ...
            "fgm",struct(Name="fgm"), ...
            "plackett",struct(Name="plackett"));
        rosenblattCase = struct( ...
            "normal",struct(Name="normal"), ...
            "student",struct(Name="t"), ...
            "clayton",struct(Name="clayton"), ...
            "gumbel",struct(Name="gumbel"), ...
            "frank",struct(Name="frank"), ...
            "joe",struct(Name="joe"), ...
            "amh",struct(Name="amh"), ...
            "galambos",struct(Name="galambos"), ...
            "fgm",struct(Name="fgm"), ...
            "plackett",struct(Name="plackett"));
        statisticCase = struct( ...
            "cvm",struct(Function="gofCvM",Field="cvm"), ...
            "ks",struct(Function="gofKS",Field="ks"), ...
            "rosenblattSnB",struct(Function="gofRosenblattSnB",Field="rosenblattSnB"), ...
            "rosenblattSnC",struct(Function="gofRosenblattSnC",Field="rosenblattSnC"), ...
            "rosenblattGamma",struct(Function="gofRosenblattGamma",Field="rosenblattGamma"), ...
            "rosenblattChisq",struct(Function="gofRosenblattChisq",Field="rosenblattChisq"), ...
            "archmSnB",struct(Function="gofArchmSnB",Field="archmSnB"), ...
            "archmSnC",struct(Function="gofArchmSnC",Field="archmSnC"), ...
            "archmGamma",struct(Function="gofArchmGamma",Field="archmGamma"), ...
            "archmChisq",struct(Function="gofArchmChisq",Field="archmChisq"));
        estimationCase = struct( ...
            "normal",struct(Name="normal",DF=5), ...
            "student",struct(Name="t",DF=5), ...
            "clayton",struct(Name="clayton",DF=5), ...
            "gumbel",struct(Name="gumbel",DF=5), ...
            "frank",struct(Name="frank",DF=5), ...
            "joe",struct(Name="joe",DF=5));
        kendallCase = struct( ...
            "cvm",struct(Method="gofKendallCvM",Field="kendallCvm"), ...
            "ks",struct(Method="gofKendallKS",Field="kendallKs"));
        d3Case = struct( ...
            "normal",struct(Name="normal"), ...
            "clayton",struct(Name="clayton"), ...
            "gumbel",struct(Name="gumbel"), ...
            "frank",struct(Name="frank"), ...
            "joe",struct(Name="joe"));
        marginCase = struct( ...
            "norm",struct(Name="norm",CompareParameters=true), ...
            "exp",struct(Name="exp",CompareParameters=true), ...
            "gamma",struct(Name="gamma",CompareParameters=false), ...
            "lnorm",struct(Name="lnorm",CompareParameters=true), ...
            "weibull",struct(Name="weibull",CompareParameters=true), ...
            "beta",struct(Name="beta",CompareParameters=true), ...
            "cauchy",struct(Name="cauchy",CompareParameters=false), ...
            "f",struct(Name="f",CompareParameters=false));
        flipCase = struct( ...
            "flip90",struct(Index=1), ...
            "flip180",struct(Index=2), ...
            "flip270",struct(Index=3));
    end

    methods (TestClassSetup)
        function loadOracle(testCase)
            root=fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(root,"src")));
            fixture=fullfile(root,"tests","reference","rOracle.json");
            testCase.Oracle=jsondecode(fileread(fixture));
        end
    end

    methods (Test)
        function cdfMatchesR(testCase,familyCase)
            oracle=testCase.Oracle;
            expected=oracle.families.(familyCase.Name);
            actual=gofcopula.copulaCDF(familyCase.Name,oracle.evaluationPoints, ...
                expected.theta,DF=expected.df);
            testCase.verifyEqual(actual,expected.cdf,AbsTol=3e-12);
        end

        function pdfMatchesR(testCase,familyCase)
            oracle=testCase.Oracle;
            expected=oracle.families.(familyCase.Name);
            actual=gofcopula.copulaPDF(familyCase.Name,oracle.evaluationPoints, ...
                expected.theta,DF=expected.df);
            testCase.verifyEqual(actual,expected.pdf,AbsTol=5e-8);
        end

        function rosenblattMatchesR(testCase,rosenblattCase)
            oracle=testCase.Oracle;
            family=oracle.families.(rosenblattCase.Name);
            actual=gofcopula.rosenblatt(rosenblattCase.Name, ...
                oracle.evaluationPoints,family.theta,DF=family.df);
            expected=oracle.rosenblatt.(rosenblattCase.Name);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end

        function rawStatisticMatchesR(testCase,statisticCase)
            oracle=testCase.Oracle;
            functionHandle=str2func("gofcopula."+statisticCase.Function);
            result=functionHandle("clayton",oracle.statisticSample,M=0, ...
                Param=1.4,ParamEst=false,DFEst=false,Margins="none");
            expected=oracle.statistics.(statisticCase.Field);
            testCase.verifyEqual(result.Tests.Statistic,expected,AbsTol=1e-10);
        end

        function piosRnMatchesR(testCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofPIOSRn("clayton",oracle.piosSample,M=0, ...
                Param=1.4,ParamEst=false,DFEst=false,Margins="none");
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.statistics.piosRn,AbsTol=1e-6);
        end

        function piosTnMatchesR(testCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofPIOSTn("clayton",oracle.piosSample,M=0, ...
                Param=1.4,ParamEst=false,DFEst=false,Margins="none",BlockSize=1);
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.statistics.piosTn,AbsTol=5e-6);
        end

        function whiteMatchesRCompatibilityMode(testCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofWhite("clayton",oracle.statisticSample,M=0, ...
                Param=1.4,ParamEst=false,DFEst=false,Margins="none", ...
                NumericMode="rCompatible");
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.statistics.white,AbsTol=5e-5);
        end

        function studentWhiteMatchesRCompatibilityMode(testCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofWhite("t",oracle.statisticSample,M=0, ...
                Param=.25,ParamEst=false,DF=5,DFEst=false,Margins="none", ...
                NumericMode="rCompatible");
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.statistics.whiteT,AbsTol=5e-4);
        end

        function pseudoLikelihoodEstimateMatchesR(testCase,estimationCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofCvM(estimationCase.Name, ...
                oracle.statisticSample,M=0,Param=.5,ParamEst=true, ...
                DF=estimationCase.DF,DFEst=false,Margins="none");
            expected=oracle.estimates.(estimationCase.Name);
            testCase.verifyEqual(result.Theta,expected,AbsTol=5e-5);
        end

        function kernelMatchesRWithFrozenModelSample(testCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofKernel("clayton",oracle.statisticSample,M=0, ...
                Param=1.4,ParamEst=false,DFEst=false,Margins="none", ...
                MJ=100,IntegrationNodes=6,KernelScale=.5, ...
                ModelSample=oracle.kernelSample);
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.statistics.kernel,AbsTol=1e-10);
        end

        function bootstrapPValueMatchesRWithFrozenSamples(testCase)
            oracle=testCase.Oracle;
            samples=oracle.bootstrap.samples;
            result=gofcopula.runTest("gofCvM","clayton",oracle.piosSample, ...
                M=size(samples,3),Param=1.4,ParamEst=true,DFEst=false, ...
                Margins="none",Seed=1,BootstrapSamples=samples, ...
                NumericMode="rCompatible");
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.bootstrap.observed,AbsTol=1e-10);
            testCase.verifyEqual(result.Tests.PValue, ...
                oracle.bootstrap.pValue,AbsTol=eps);
        end

        function fixtureRecordsExactRPackage(testCase)
            metadata=testCase.Oracle.metadata;
            testCase.verifyEqual(metadata.gofCopula,'0.4.3');
            testCase.verifyEqual(metadata.copula,'1.1.7');
        end

        function kendallStatisticMatchesR(testCase,kendallCase)
            % The Kendall statistics against the frozen 500-draw reference
            % copula values, exactly as gofCopula's bootstrap consumes them.
            oracle=testCase.Oracle;
            options=struct(ReferenceCopulaValues=oracle.kendallReference, ...
                NumericMode="rCompatible");
            model=gofcopula.CopulaModel("clayton",Theta=1.4,EstimateTheta=false);
            actual=gofcopula.internal.statistics.computeStatistic( ...
                kendallCase.Method,oracle.statisticSample,model,options);
            testCase.verifyEqual(actual, ...
                oracle.statistics.(kendallCase.Field),AbsTol=1e-12);
        end

        function trivariateFamilyMatchesR(testCase,d3Case)
            oracle=testCase.Oracle;
            entry=oracle.d3.(d3Case.Name);
            dispersion="unstructured";
            if d3Case.Name=="normal", dispersion="exchangeable"; end
            cdf=gofcopula.copulaCDF(d3Case.Name,oracle.evaluationPoints3, ...
                entry.theta,Dispersion=dispersion);
            pdf=gofcopula.copulaPDF(d3Case.Name,oracle.evaluationPoints3, ...
                entry.theta,Dispersion=dispersion);
            Z=gofcopula.rosenblatt(d3Case.Name,oracle.evaluationPoints3, ...
                entry.theta,Dispersion=dispersion);
            % R's pmvnorm in d=3 is randomized quasi-Monte-Carlo (~1e-6);
            % the Archimedean CDFs are analytic and far tighter.
            testCase.verifyEqual(cdf,entry.cdf,AbsTol=5e-6);
            testCase.verifyEqual(pdf,entry.pdf,RelTol=5e-8);
            testCase.verifyEqual(Z,entry.rosenblatt,AbsTol=1e-9);
        end

        function trivariateStatisticsMatchR(testCase,d3Case)
            oracle=testCase.Oracle;
            entry=oracle.d3.(d3Case.Name);
            runOne=@(test) gofcopula.runTest(test,d3Case.Name, ...
                oracle.statisticSample3,M=0,Param=entry.theta, ...
                ParamEst=false,DFEst=false,Margins="none", ...
                NumericMode="rCompatible").Tests.Statistic;
            testCase.verifyEqual(runOne("gofCvM"),entry.cvm,AbsTol=1e-10);
            testCase.verifyEqual(runOne("gofKS"),entry.ks,AbsTol=1e-9);
            testCase.verifyEqual(runOne("gofRosenblattSnB"),entry.rosenblattSnB,AbsTol=1e-9);
            testCase.verifyEqual(runOne("gofRosenblattSnC"),entry.rosenblattSnC,AbsTol=1e-9);
            testCase.verifyEqual(runOne("gofRosenblattGamma"),entry.rosenblattGamma,AbsTol=1e-8);
            testCase.verifyEqual(runOne("gofRosenblattChisq"),entry.rosenblattChisq,AbsTol=1e-8);
        end

        function trivariateEstimateMatchesR(testCase,d3Case)
            oracle=testCase.Oracle;
            entry=oracle.d3.(d3Case.Name);
            result=gofcopula.runTest("gofCvM",d3Case.Name, ...
                oracle.estimationSample3,M=0,Param=0.5,ParamEst=true, ...
                DFEst=false,Margins="none");
            testCase.verifyEqual(result.Theta,entry.estimate,AbsTol=5e-4);
        end

        function ranksPipelineMatchesR(testCase)
            % The rCompatible mode must reproduce R's rank-margins
            % bootstrap chain exactly: pseudo-observations for the
            % observed statistic, raw (never re-ranked) replicates.
            oracle=testCase.Oracle;
            samples=oracle.ranksPipeline.samples;
            result=gofcopula.runTest("gofCvM","clayton", ...
                oracle.ranksPipeline.rawData,M=size(samples,3), ...
                ParamEst=true,DFEst=false,Margins="ranks",Seed=1, ...
                BootstrapSamples=samples,NumericMode="rCompatible");
            testCase.verifyEqual(result.Theta, ...
                oracle.ranksPipeline.theta,AbsTol=5e-5);
            % Optimizer-limited: the fitted theta agrees to ~1e-8, which
            % propagates linearly into the statistic.
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.ranksPipeline.observed,AbsTol=1e-8);
            testCase.verifyEqual(result.Tests.PValue, ...
                oracle.ranksPipeline.pValue,AbsTol=eps);
            % corrected mode re-ranks the same replicates: the p-value
            % must differ (this is the calibration fix).
            corrected=gofcopula.runTest("gofCvM","clayton", ...
                oracle.ranksPipeline.rawData,M=size(samples,3), ...
                ParamEst=true,DFEst=false,Margins="ranks",Seed=1, ...
                BootstrapSamples=samples,NumericMode="corrected");
            testCase.verifyNotEqual(corrected.Tests.PValue, ...
                result.Tests.PValue);
        end

        function whiteStudentModerateSampleMatchesR(testCase)
            oracle=testCase.Oracle;
            result=gofcopula.gofWhite("t",oracle.whiteT100.sample,M=0, ...
                Param=oracle.whiteT100.par,ParamEst=false, ...
                DF=oracle.whiteT100.df,DFEst=false,Margins="none", ...
                NumericMode="rCompatible");
            testCase.verifyEqual(result.Tests.Statistic, ...
                oracle.whiteT100.statistic,RelTol=1e-3);
        end

        function marginFitMatchesR(testCase,marginCase)
            % R fits margins by constrOptim maximum likelihood; the port
            % uses fitdist. Optima agree, optimizers differ, so the
            % transformed values are compared with a small-sample
            % tolerance. t and chisq margins are documented deviations
            % (different parameterizations) and are not compared.
            oracle=testCase.Oracle;
            entry=oracle.margins.(marginCase.Name);
            [u,parameters]=gofcopula.internal.estimation.transformMargins( ...
                entry.data(:),marginCase.Name);
            testCase.verifyEqual(u,entry.u,AbsTol=2e-2);
            if marginCase.CompareParameters
                actual=marginParameterVector(marginCase.Name,parameters{1});
                testCase.verifyEqual(actual,entry.parameters(:).',RelTol=5e-2);
            end
        end

        function flipConventionMatchesR(testCase,flipCase)
            % Pins the R rotation convention (90 -> (1-u2, u1), etc.).
            oracle=testCase.Oracle;
            entry=oracle.flip(flipCase.Index);
            result=gofcopula.runTest("gofCvM","frank", ...
                oracle.statisticSample,M=0,ParamEst=true,DFEst=false, ...
                Margins="none",Flip=entry.angle,NumericMode="rCompatible");
            testCase.verifyEqual(result.Theta,entry.theta,AbsTol=5e-5);
            % Optimizer-limited through the fitted parameter.
            testCase.verifyEqual(result.Tests.Statistic,entry.cvm,AbsTol=5e-8);
        end

        function tevJointEstimateMatchesR(testCase)
            % The t-EV (theta, df) likelihood has a long, nearly flat
            % ridge: R and the port stop at different ridge points with
            % indistinguishable fits. The meaningful invariants are that
            % the port's pseudo-likelihood is at least as high as at R's
            % estimate and that both estimates imply the same Pickands
            % dependence function.
            oracle=testCase.Oracle;
            result=gofcopula.runTest("gofCvM","tev",oracle.tev.sample, ...
                M=0,Param=0.3,ParamEst=true,DF=8,DFEst=true,Margins="none");
            logLik=@(theta,df) sum(gofcopula.copulaPDF("tev", ...
                min(max(oracle.tev.sample,eps),1-eps),theta,DF=df,Log=true));
            portLik=logLik(result.Theta,result.DegreesOfFreedom);
            rLik=logLik(oracle.tev.theta,oracle.tev.df);
            testCase.verifyGreaterThanOrEqual(portLik,rLik-1e-3);
            w=(0.02:0.02:0.98).';
            Aport=gofcopula.internal.copulas.evDependence("tev",w, ...
                result.Theta,result.DegreesOfFreedom);
            Ar=gofcopula.internal.copulas.evDependence("tev",w, ...
                oracle.tev.theta,oracle.tev.df);
            testCase.verifyEqual(Aport,Ar,AbsTol=2e-3);
        end
    end
end

function vector = marginParameterVector(family, parameters)
switch family
    case "exp"
        vector = 1 ./ parameters.Distribution.mu; % R stores the rate
    case "weibull"
        % R stores (shape, scale); fitdist Weibull stores (A=scale, B=shape).
        vector = [parameters.Distribution.B, parameters.Distribution.A];
    case "norm"
        vector = [parameters.Distribution.mu, parameters.Distribution.sigma];
    case "lnorm"
        vector = [parameters.Distribution.mu, parameters.Distribution.sigma];
    case "beta"
        vector = [parameters.Distribution.a, parameters.Distribution.b];
    otherwise
        error("gofcopula:test:UnexpectedMarginFamily", ...
            "No parameter mapping for %s.", family);
end
end
